//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace updaterFactuWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        // Config Incrementales
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool autoIncrementales {
                get {
                    return ((bool)(this["autoIncrementales"]));
                }
                set {
                    this["autoIncrementales"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("3600")]
            public int timeIncrementales {
                get {
                    return ((int)(this["timeIncrementales"]));
                }
                set {
                    this["timeIncrementales"] = value;
                }
            }

        // Config Pedidos
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool autoPedidos {
                get {
                    return ((bool)(this["autoPedidos"]));
                }
                set {
                    this["autoPedidos"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("3600")]
            public int timePedidos {
                get {
                    return ((int)(this["timePedidos"]));
                }
                set {
                    this["timePedidos"] = value;
                }
            }


        // Config Fotos
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool autoFotos {
                get {
                    return ((bool)(this["autoFotos"]));
                }
                set {
                    this["autoFotos"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("3600")]
            public int timeFotos {
                get {
                    return ((int)(this["timeFotos"]));
                }
                set {
                    this["timeFotos"] = value;
                }
            }


        // Config Total
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool autoTotal {
                get {
                    return ((bool)(this["autoTotal"]));
                }
                set {
                    this["autoTotal"] = value;
                }
            }

            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("01/01/1979 00:00:00")]
            public string timeTotal {
                get {
                    return ((string)(this["timeTotal"]));
                }
                set {
                    this["timeTotal"] = value;
                }
            }



        // Config API
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:1337/api/")]
            public string api {
                get {
                    return ((string)(this["api"]));
                }
                set {
                    this["api"] = value;
                }
            }
        
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("")]
            public string token {
                get {
                    return ((string)(this["token"]));
                }
                set {
                    this["token"] = value;
                }
            }
        

        // Config Factusol
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("C:\\Software DELSOL\\FactuSOL\\Datos\\FS")]
            public string path {
                get {
                    return ((string)(this["path"]));
                }
                set {
                    this["path"] = value;
                }
            }
        
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("XD1")]
            public string company {
                get {
                    return ((string)(this["company"]));
                }
                set {
                    this["company"] = value;
                }
            }
        
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("2020")]
            public string year {
                get {
                    return ((string)(this["year"]));
                }
                set {
                    this["year"] = value;
                }
            }
        

        // Config global
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute("False")]
            public bool initmin {
                get {
                    return ((bool)(this["initmin"]));
                }
                set {
                    this["initmin"] = value;
                }
            }
        
            [global::System.Configuration.UserScopedSettingAttribute()]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Configuration.DefaultSettingValueAttribute(".accdb")]
            public string dbExtension {
                get {
                    return ((string)(this["dbExtension"]));
                }
                set {
                    this["dbExtension"] = value;
                }
            }
        
    }
}
